### ISSUE TITLE
Release the version to CPAN

### ISSUE THREAD

**Issue by JJ** [dsully/perl-mp3-info#2]
It need be only a maintenance release, but it would be useful to actually have this version. I can help you with something else, if needed.

**Comment by dsully** [comment]
Please, I'm on vacation right now & haven't really been doing Perl for the last 10 years.

**Comment by JJ** [comment]
OK; I'll work through the docs and will try to fix some outstanding RT bugs. You still have the credentials to upload to CPAN?

**Comment by dsully** [comment]
Yes.

**Comment by JJ** [comment]
Great :-)

**Comment by JJ** [comment]
Hi again, is there any problem with updating the version in CPAN? Do you want me to take over?

**Comment by paultcochrane** [comment]
Agreed, it would be great if this were updated on CPAN. You just need to give @JJ CO-MAINT on [PAUSE](https://pause.perl.org); I bet he'd do a great job of maintaining the module!

**Comment by JJ** [comment]
I'd be happy to.
